name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"  # todo dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: dancarvofc
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, repositories
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
